#!/usr/bin/env npx tsx
/**
 * Bulk import PubChem data for seed ingredient list into D1-compatible SQL.
 *
 * Uses PUG REST API to resolve ingredient names → CID, MolecularFormula, MolecularWeight, IUPACName.
 * Processes names in concurrent batches of 5 (PubChem allows 5 req/sec).
 *
 * Usage:
 *   npx tsx scripts/import-pubchem.ts
 *
 * Input:  scripts/ingredient-seed-list.json
 * Output: scripts/d1-ingredients-ref-pubchem.sql
 *
 * Then import:
 *   npx wrangler d1 execute alzhal-ingredients-ref --remote --file=scripts/d1-ingredients-ref-pubchem.sql
 */

import { readFileSync, createWriteStream } from 'fs'
import path from 'path'

const INPUT_FILE = path.join(process.cwd(), 'scripts', 'ingredient-seed-list.json')
const OUTPUT_FILE = path.join(process.cwd(), 'scripts', 'd1-ingredients-ref-pubchem.sql')

const SQL_BATCH_SIZE = 20 // rows per INSERT statement
const CONCURRENCY = 5 // concurrent PubChem requests (PubChem allows 5/sec)
const BATCH_DELAY_MS = 1100 // delay between concurrent batches (~5 req/sec)
const FETCH_TIMEOUT = 10000

function escapeSQL(str: string): string {
  return str.replace(/'/g, "''")
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms))
}

async function fetchPubChem(name: string): Promise<{
  cid: number
  molecular_formula: string | null
  molecular_weight: string | null
  iupac_name: string | null
} | null> {
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT)

  try {
    const encodedName = encodeURIComponent(name)
    const url = `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/${encodedName}/property/MolecularFormula,MolecularWeight,IUPACName/JSON`

    const res = await fetch(url, {
      headers: { 'User-Agent': 'Alzhal-Import/1.0' },
      signal: controller.signal,
    })

    clearTimeout(timeout)

    if (!res.ok) return null

    const data = await res.json()
    const props = data?.PropertyTable?.Properties?.[0]
    if (!props) return null

    return {
      cid: props.CID || 0,
      molecular_formula: props.MolecularFormula || null,
      molecular_weight: props.MolecularWeight ? String(props.MolecularWeight) : null,
      iupac_name: props.IUPACName || null,
    }
  } catch {
    clearTimeout(timeout)
    return null
  }
}

interface IngredientRow {
  name: string
  name_original: string
  pubchem_cid: number
  molecular_formula: string | null
  molecular_weight: string | null
  iupac_name: string | null
}

async function main() {
  console.log('Loading seed list...')
  const names: string[] = JSON.parse(readFileSync(INPUT_FILE, 'utf-8'))
  console.log(`Loaded ${names.length} ingredient names`)
  console.log(`Estimated time: ${((names.length / CONCURRENCY * BATCH_DELAY_MS) / 1000 / 60).toFixed(0)} minutes`)

  const out = createWriteStream(OUTPUT_FILE)
  out.write('-- PubChem data import for ingredients reference\n')
  out.write('-- Auto-generated by import-pubchem.ts\n\n')

  let hits = 0
  let misses = 0
  let errors = 0
  let sqlBatch: IngredientRow[] = []

  function flushSqlBatch() {
    if (sqlBatch.length === 0) return

    const values = sqlBatch.map(row => {
      const mf = row.molecular_formula ? `'${escapeSQL(row.molecular_formula)}'` : 'NULL'
      const mw = row.molecular_weight ? `'${escapeSQL(row.molecular_weight)}'` : 'NULL'
      const iupac = row.iupac_name ? `'${escapeSQL(row.iupac_name)}'` : 'NULL'
      return `('${escapeSQL(row.name)}', '${escapeSQL(row.name_original)}', ${row.pubchem_cid}, ${mf}, ${mw}, ${iupac})`
    })

    out.write(
      `INSERT OR IGNORE INTO ingredient_reference (name, name_original, pubchem_cid, molecular_formula, molecular_weight, iupac_name)\nVALUES\n  ${values.join(',\n  ')};\n\n`
    )
    sqlBatch = []
  }

  const startTime = Date.now()

  // Process in concurrent batches
  for (let i = 0; i < names.length; i += CONCURRENCY) {
    const batch = names.slice(i, i + CONCURRENCY)

    const results = await Promise.all(
      batch.map(async (name) => {
        try {
          const data = await fetchPubChem(name)
          return { name, data, errored: false }
        } catch {
          return { name, data: null, errored: true }
        }
      })
    )
    errors += results.filter(r => r.errored).length

    for (const { name, data } of results) {
      if (data && data.cid) {
        hits++
        sqlBatch.push({
          name: name.toLowerCase(),
          name_original: name,
          pubchem_cid: data.cid,
          molecular_formula: data.molecular_formula,
          molecular_weight: data.molecular_weight,
          iupac_name: data.iupac_name,
        })

        if (sqlBatch.length >= SQL_BATCH_SIZE) {
          flushSqlBatch()
        }
      } else {
        misses++
      }
    }

    // Progress logging every 500 names
    const processed = Math.min(i + CONCURRENCY, names.length)
    if (processed % 500 < CONCURRENCY || processed === names.length) {
      const elapsed = (Date.now() - startTime) / 1000
      const rate = processed / elapsed
      const remaining = (names.length - processed) / rate
      console.log(
        `Progress: ${processed}/${names.length} (${hits} hits, ${misses} misses) ` +
        `[${rate.toFixed(1)} names/sec, ~${(remaining / 60).toFixed(0)} min remaining]`
      )
    }

    // Rate limit: wait between batches
    await sleep(BATCH_DELAY_MS)
  }

  // Flush remaining
  flushSqlBatch()
  out.end()

  const totalTime = ((Date.now() - startTime) / 1000 / 60).toFixed(1)
  console.log(`\nDone in ${totalTime} minutes!`)
  console.log(`  Hits: ${hits}`)
  console.log(`  Misses: ${misses}`)
  console.log(`  Errors: ${errors}`)
  console.log(`  Hit rate: ${((hits / (hits + misses)) * 100).toFixed(1)}%`)
  console.log(`  Output: ${OUTPUT_FILE}`)
}

main().catch(console.error)
